### ISSUE TITLE
Call Schema pre() method

### ISSUE THREAD

**Issue by zabojad** [clemos/haxe-js-kit#103]
Hi !

I'm quite lost with the Mongoose externs...

Here is a javascript version of what I would like to do:
```
var mongoose = require('mongoose');

// Define our user schema
var UserSchema = new mongoose.Schema({
  username: String,
  password: String
});

// Execute before each user.save() call
UserSchema.pre('save', function(callback) {
  var user = this;

  // Break out if the password hasn't changed
  if (!user.isModified('password')) return callback();

  console.log("password has changed: "+user.password);
});

// Export the Mongoose model
module.exports = mongoose.model('User', UserSchema);
```

Now, here is what I have in my haxe project:
```
typedef UserData = {
    username : String,
    password : String
}

@:schemaOptions({
    versionKey: false
})
class User extends Model<UserData> { }
class UserManager extends Manager<UserData, User> { }

class UserDao {

	public function new(db : Mongoose) {

		md = UserManager.build(db, "User");
	}

	public var md : TModels<UserData, User>;
}
```

I see in the Mongoose externs that the [pre method is defined](https://github.com/clemos/haxe-js-kit/blob/master/js/npm/mongoose/Schema.hx#L19). But how can I call it ? And in its callback, how will I be able to access the user instance it concerns ("this" in the raw javascript version)? 

Thanks in advance !

**Comment by clemos** [comment]
I think the easiest (untested, off the top of my head) way to access `pre()` is via the model:
```haxe
md.schema.pre("save", function(...){});
```
This is because the Schema instance is created under the hood via a macro, so you can't access it before model creation like you would in native JS.
But it should be quite similar, in the end.

Regarding JS's native `this`, you can use `js.Kit.self` to access it.
Unfortunately, you'll need to type it manually (to a `UserModel`, I guess):
```haxe
var user : UserModel = js.Kit.self;
``` 

I know the Mongoose externs are pretty confusing. 
Unfortunately, the mongoose authors designed their library in a very JS-centric way that makes it difficult to "adapt" to a stricter language such as Haxe.

**Comment by zabojad** [comment]
It works ! Thank you !

**Comment by clemos** [comment]
Feel free to write some docs, it would be pretty useful :D

**Comment by zabojad** [comment]
I was thinking about proposing it to you but finally thought you are not a doc guy and wouldn't probably care...

So I was wrong :) ! I will indeed probably PR some doc page about the use of mongoose externs... What about a /docs folder in the js-kit repo ?

**Comment by clemos** [comment]
Yes, that would be great.
I hate writing docs, so I particularily appreciate people contributing this way ;)
