### ISSUE TITLE
Error handling suggestion for @async

### ISSUE THREAD

**Issue by ciscoheat** [clemos/haxe-js-kit#123]
I love the `@async` feature, but I'm tired of the error testing and callback passing. What do you think about adding error handling in the metadata? Something like:

```haxe
public function start(cb : Error -> Void) {
    var err, client = @async(err => cb) Soap.createClient('https://some/service.asmx?wsdl');
    // ...
}
```

With this `(err => cb)` construct, it will generate this code:

```haxe
Soap.createClient('https://some/service.asmx?wsdl', function(err, client) {
    if(err != null) return cb(err);
    // ...
});
```

I'm not sure how to handle callback signatures with different number of parameters though. What do you think about this idea?

**Comment by ciscoheat** [comment]
Here's an idea how to solve the different parameters:

```haxe
// Assuming cb is Error -> String -> Void
var err, result = @async(err, null => cb) some.method()
```

I've done some testing, it was quite simple to implement, about 20 lines in `util/Async.hx` (including useful error messages).

**Comment by clemos** [comment]
Honestly, this `@async` stuff is all about making the syntax easier, KISS-er, while keeping the macro basic. So I don't really like either of your proposals as-is.
OTOH, I would also like to see an elegant solution for error handling.

Also, I don't see any situation where `cb` shouldn't be `Error -> String -> Void` in the first place.
In this case, it's easy to skip the `if` and just `cb( err, result )`.
Then I think it would be nice to be able to `@async cb( err, result ) = some.method();` ?

ITOH, maybe the following would be nice too, maybe closer to your first idea : 
`var cb( err ), result = @async some.method();`
or
`@async cb( err ), result = some.method();`

Random / possibly irrelevant idea : 
```
@async switch Soap.createClient('...') {
  case [null, result]: // do something with result
  case [err,_]: // handle error
}
```
I don't like it that much, though, because it adds indentation, 
but I like the FP style of it.

Let's discuss :p

**Comment by clemos** [comment]
About the second idea, how about: 
```
@async switch Soap.createClient('...') {
  case @success( a , b ): // do something with a and b, given the callback has extra values
  case @success( a, b ) if a == "whatever": // guards
  case @error( err ): // handle error
  case @error( { code : 404, message : message } ): // pattern matching
}
```

I also don't want to go too far into something too complex,
because I'm pretty sure Juraj's tink_* has something similar, while much more solid and flexible...

**Comment by clemos** [comment]
About the current syntax, and given all this : 
I'd actually love to drop the `var`, or have something like

**Comment by clemos** [comment]
misclicked

**Comment by ciscoheat** [comment]
I this idea, it's nicer than the one I suggested:

```haxe
var cb( err ), result = @async some.method();

// And for callbacks with multiple parameters
var cb(err, null), result = @async some.method();
```

Dropping var is fine for me, but I don't think it makes things that much worse, since it's consistent with normal variable declaration.

If you think the syntax is ok, I'll start working on it and will make a PR.

**Comment by ciscoheat** [comment]
Unfortunately that is invalid syntax. :(

**Comment by fullofcaffeine** [comment]
Oh, the idea was great, So that's a no-no? :/

**Comment by clemos** [comment]
We can probably figure something out ;)

**Comment by ciscoheat** [comment]
Ok, here's another take: Leaving KISS aside for a moment, I think semantics is also a quite important part of expressing yourself in code. So what would an uninitialized reader think about this:

```haxe
var error = @async(error => callback) some.method();
```

Maybe: "An asynchronous call, errors goes to callback"

Compared to:

```haxe
var callback(error) = @async some.method();
```

This looks more like a method call before the async call?

What would your interpretation be of these? Unbiased, I expect. ;)

Also: `@async(error => callback) some.method()` looks very good, but takes more work.

**Comment by clemos** [comment]
I've been reading the whole thread again, and you're right it's all very confusing.

Back to your first proposal, I think it's already very misleading / error prone, mainly because it's not clear at all that there is a possible `return` / break: most of the time, with `@async` you expect the rest of your code to eventually run anyway.
It feels like some kind of hidden `try/catch` block...

Also, your proposal somehow assumes the first callback arguments is an error.
But `@async` can be used in many other situations, in theory : 
```
{ 
   var req, res = @:async express.get("stuff/:id"); 
   res.end("Hello");
}
```
(Not really using it like this myself, not sure it even works like it should, but still...)

Also, the more I think about, the more I think having only an error in your callback is an anti-pattern.
I've never used it myself, and pretty much fail to see the benefit.
... *except* if you want to use promises ;)

So IMHO, the ultimate solution to your problem is in promises, really :p 
That's why `switch` constructs popped to me at first.
How about that ?
```haxe
var result = switch @async some.method() {
   case [null, result] : result;
   case [err, _] : return callback( err ); null;
}
```

In any case, I think your problem goes far beyond what `@async` is about, 
and you should look into more complete FP-style solutions.

**Comment by ciscoheat** [comment]
True, it's based on the most frequent use case I have: If something goes wrong, pass it on and exit. It's not a general-purpose solution.

**Comment by clemos** [comment]
PS:
With [`promisify`](https://www.npmjs.com/package/es6-promisify), we could : 
```haxe
using Promisify;
var result = some.method.promisify()("arg1","arg2").catch( callback ).then(); 
```
Not even sure it works in the current `@async` implementation, but it should...

**Comment by ciscoheat** [comment]
What happened to KISS? :)

**Comment by clemos** [comment]
Haha simple != concise :p

**Comment by ciscoheat** [comment]
Also true, but that code is rather an example of redundancy than conciseness. And with promises, it even turns into verbosity... I remember this discussion: https://groups.google.com/d/msg/haxelang/OiKbnxX4Wtk/Lh4PS2mSv84J

**Comment by clemos** [comment]
I don't like promises either;
You are the one who brought me to promises with your error callback ;)

**Comment by ciscoheat** [comment]
No I don't want to catch anything really, in this case I want a return value, and a way of handling it in the Node callback style: http://fredkschott.com/post/2014/03/understanding-error-first-callbacks-in-node-js/
