### ISSUE TITLE
Merge/test strategy for the packages?

### ISSUE THREAD

**Issue by ciscoheat** [clemos/haxe-js-kit#29]
Hi, soon I'll have a large bunch of packages ready to be merged from https://github.com/ciscoheat/meadowlark/tree/master/js-kit/js, how would you like them to be reviewed and pull-requested? Not all have a complete API but they are all working fine.

I'm using an abstract class here for settings, would you like me to use an inline static string in the class instead? https://github.com/ciscoheat/meadowlark/blob/master/js-kit/js/npm/express/Morgan.hx

I haven't made packages for all subclasses, for example here with `CsurfOptions`. Is that ok still? https://github.com/ciscoheat/meadowlark/blob/master/js-kit/js/npm/express/Csurf.hx

js.npm.express, connect or neither? Sometimes I'm struggling where to put the class. Any guidelines?

**Comment by clemos** [comment]
Looks awesome :D 
I guess it would be nice to create a branch based on `haxe-js-kit/dev`, copy the externs there, and make a PR.
I have reviewed a few, and it seems really good.

Currently, there is no unit testing for the externs, but I guess it will very soon be necessary... 
I guess the way to go would be to create as many small Haxe/NodeJS apps as possible (like currently in `test`): if they compile, it's already something :)
Then, to go further, we could write some unit-tests for testing these apps.
But for now, let's trust "they are all working fine" :D 

Abstract classes for settings are perfect.
I've learned about them not so long ago, so that's why there are currently few of them in the lib.
But it's definitely the way to go for enum-like string values.

`CurfOptions` is perfect where it is (no need to make 1 class per module).

As for `js.npm.express` or `connect` : 
I used to put classes from the same npm lib in a sub-package (like `express.Session`)
Now that Express has split into separate npm libs, I think it makes sense to:
* put "official" Express related npm libs (those hosted on github/expressjs) in the `js.npm.express` package (`morgan`, `csurf`, ...)
* put "non official" Express related npm libs (the rest) in `js.npm` (`mongoose-session`)
So the externs you put in `js.npm.connect` should actually go in `js.npm`, except for `vhost` that is officially "part" of `expressjs`
The caveat of this approach is that the `js.npm` namespace has lots of classes, but I guess it's fine like that for now.
What do you think ?

About `formidable`, you should remove this : 
https://github.com/ciscoheat/meadowlark/blob/master/js-kit/js/npm/Formidable.hx#L11-L13
and use
`implements npm.Package.RequireNamespace<'formidable','~1.0.16'>`
in both `formidable` packages.
I guess you can then simply remove the main `Formidable` class since it will have no method.

**Comment by ciscoheat** [comment]
Glad you like it. :) I'll make the changes according to your suggestions. I'm glad to get rid of the connect package to avoid confusion.

Should I put `RequireNamespace` on all classes in a sub-package, or only for those with that special usage? What about https://github.com/ciscoheat/meadowlark/blob/master/js-kit/js/npm/Zombie.hx and its package for example?

I'll also change the version range to ^ since it's the default for npm.

**Comment by clemos** [comment]
I guess we're good here :)
