### ISSUE TITLE
Any dev -> master -> haxelib roadmap?

### ISSUE THREAD

**Issue by ciscoheat** [clemos/haxe-js-kit#59]
As the readme prominently displays: **Warning : This is a work in progress and is definitely not stable nor complete !**

I kind of disagree. :) I've been using the dev branch for a long time, it's simple and useful, and if I find any problems I submit a PR and it gets accepted quickly. 

My plan is to use haxe-js-kit in a large project soon, so I'm curious if there will be a dev -> master merge soon, to stabilize the project? What are the dev/master differences right now, and why? 

I was also thinking about a haxelib release, but maybe that depends on the [official haxe/node externs](https://github.com/HaxeFoundation/hxnodejs)?

As I said in #54 I'm happy to set up a Travis environment with the tests, so if that can help I'll start working on that.

**Comment by clemos** [comment]
Yes I agree with you.
I'd like to dump our core node.js externs in favor of the official ones first if possible, though.
Then we can merge all this mess to one branch and go forward....

**Comment by ciscoheat** [comment]
Sounds like a good plan. I haven't used the official ones, are they compatible with js-kit without any hassle? If so, how about a new branch that will do a (fully tested) clean up and prepare for a master merge?

Or maybe we can go even further: A related project is https://github.com/abedev/npm , is it similar enough to create a joint effort? What do you say @fponticelli ?

**Comment by fponticelli** [comment]
Sure thing, let's make it happen if we can. The only thing that I believe no one solved properly (me included) is versioning the libraries.

**Comment by ProG4mr** [comment]
:+1: for this

**Comment by dionjwa** [comment]
+1
Also, if you want to use the 'nodejs' haxelib, where I'm currently the owner, I'm all for giving it up. I'm for making this the main supported haxe+node.js repo. That way, you get the -D nodejs compiler flag automatic. Also agree with this being stable enough for production.

**Comment by ciscoheat** [comment]
That's great to hear @dionjwa ! I can start experimenting with a fork and abenpm/nodejs merge, but if @clemos is hesitant I don't want to embark on "yet another node project", making things even more confusing for the users... What do you say clemos?

**Comment by dionjwa** [comment]
Yeah. Let's start solidifying around a single project, and not fragment anymore.

**Comment by clemos** [comment]
It would be great that current hxnodejs would be published in haxelib as 'nodejs'. Is that what you mean ?
Otherwise, about haxe-js-kit, I would totally welcome any PR that would help me do what we agreed to do remove node.js in favor of hxnodejs.
I currently don't have much time for that project, but am still pretty excited about it :D and hopefully I'll be able to come back to it soon...

**Comment by ProG4mr** [comment]
For the record I'm working with meteor haxe externs and released them [as an haxelib](https://github.com/ProG4mr/hxmeteor), for now it makes sense to keep it like that while its still growing, later I'd be glad to move it to js-kit when the time is right.

**Comment by fullofcaffeine** [comment]
Tiago, nice to know you're working on Meteor externs! I have been playing
with Meteor (vanillla javascript) and I really liked it so far, too.
There's an old message that I sent to the haxelang mailing list, that might
have some old albeit useful information for you, maybe:
https://groups.google.com/forum/#!topic/haxelang/8bdji7rakTA.

Solidifying haxe-js-kit as *the* nodejs framework for haxe would be great.
I guess the name is also a bit confusing right now, not very SEOish.

Clemos, Andreas, keep up the great work!

**Comment by clemos** [comment]
About the "haxe-js-kit" name, I changed it on purpose to remove the reference to node.
That's because the project turns (slowly) into a more fullstack / isomorphic thing, including client-side libraries, atom-shell/electron, etc.
I think it's somehow better, because Haxe is obviously very good at isomorphism already, and it can really help evolve a plain JS prototype app into an industry-standard maintainable application (web, but also desktop, native, ...), which I believe can seduce a lot of JS or fullstack devs.
That's also why I think it would make sense to redirect people looking for nodejs to hxnodejs (= nodejs on haxelib), 
while we will try to get those looking for higher-level stuff such as Express, Electron, React.
At some point, I think it can make sense to make it a Github organization and split the repo into several sub-projects, pretty much like abe does. 
But once again, that's another story, and I don't really have time to execute this ambitious plan, for now ;)

**Comment by ProG4mr** [comment]
Hey @fullofcaffeine glad you also like meteor (its a great lib for reactive web pages), there were no externs for meteor and few examples, in the project i mentioned i also ported some of the meteor examples to haxe including a template to build applications using iron router and other libraries. 

Its still in development but works nicely already, could be improved with some macros tho. Cheers.

**Comment by clemos** [comment]
I'm closing this issue, as haxelib -> master -> dev are in line, now.
